name: otp_firebase
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  pin_code_text_field:
  http:
  shared_preferences:
  provider:
  mobx:
  flutter_mobx:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
flutter:
  uses-material-design: true
